- public/vis.js
> Mark as BETA

- package.json
- public/vislib/_map.js
[#6650](https://github.com/sirensolutions/kibi-internal/issues/6650) error clicking on map after creating polygon
Upgraded leaflet in kibi investigate, making relevant changes.
Have tested other plugins as well (Which rely on leaflet). Please merge this AFTER this is merged :- [#6942](https://github.com/sirensolutions/kibi-internal/pull/6942)
> #6650 BugFix: Upgraded leaflet in kibana, made relevant changes.

- public/resp_processor.js
[#9391](https://github.com/sirensolutions/kibi-internal/pull/9391)
> Prevent mutation of ES response.

- public/directives/savedSearch.html
- public/directives/tooltipFormatter.html
- public/directives/wmsOverlay.html
- public/options.html
First attempt at removal of Kibana references outlined in sirensolutions/kibi-internal/issues/9131 
sirensolutions/kibi-internal/issues/9238 also covered in this PR. It was overlapping to some extent.
> Removing references to Kibana v1

- public/tooltip/popupVisualize.js
- public/tooltip/visTooltip.js
- public/vis.less
- public/visController.js
Still working on why filters apply to the map, but do not apply to the Record Table.
> Record Table now appearing on Visualization Tooltip

- public/POIs.js
- public/tooltip/popupVisualize.js
- public/tooltip/visTooltip.js
- public/vis.less
- public/visController.js
Still need to fix error that happens when no POIs are present
> POI layer re-rendering each map canvas extent change

- public/POIs.js
- public/directives/savedSearch.html
- public/vis.less
- public/visController.js
- public/vislib/_map.js
Fix for https://github.com/sirensolutions/kibi-internal/issues/9548
> Aggregations now do not draw if no documents are present

- public/POIs.js
- public/directives/savedSearch.html
- public/vis.less
- public/visController.js
- public/vislib/_map.js
Translation of Kibana DSL to ES DSL (for use in Federate) for handling join queries in WMS requests
> WIP Translation of Kibana DSL to ES DSL for WMS request (issue

- public/vis.less
PR for https://github.com/sirensolutions/kibi-internal/issues/9528
> Nesting all ETM CSS in .etm-vis

- public/directives/savedSearch.html
- public/vis.less
Fix for https://github.com/sirensolutions/kibi-internal/issues/9666. 
Previously, the popup content selection did not appear, they now to as per GIF.
> Fixing popup content tooltip for POI layers

- public/tooltip/visTooltip.js
Should be merged with the kibi/internal PR: 
https://github.com/sirensolutions/kibi-internal/pull/9772
> Record table popup filtering based on geohash hover

- public/directives/tooltipFormatter.html
- public/directives/tooltipFormatter.js
- public/options.html
- public/tooltip/visTooltip.js
Addressing https://github.com/sirensolutions/kibi-internal/issues/9262
Removal of tooltip as it was inaccurate and appearing in the wrong place.  Tooltips also changed.
> Addressing issue 9262

- public/POIs.js
- public/directives/savedSearch.html
Implementing the discussion here: 
https://github.com/sirensolutions/kibi-internal/issues/10206
Looks like this:
> Increasing POI placeholder default and changing the exceeded message

- public/vis.less
- public/vislib/_map.js
**Change removes the border below:**
**To**
**A more sinister issue has been exposed. This is WIP for now**
> [WIP] [Merge after release] Removal of ETM border

- package.json
Compare to https://github.com/sirensolutions/enhanced_tilemap/pull/68
> Bump version to 10.3.1-SNAPSHOT

- package-lock.json
- package.json
- public/callbacks.js
- public/lib/leaflet.measurescale/L.Control.MeasureScale.js
- public/lib/leaflet.setview/L.Control.SetView.js
- public/lib/leaflet.sync/L.Map.Sync.js
- public/vislib/_map.js
To be merged with https://github.com/sirensolutions/kibi-internal/pull/10575
> Bumping leaflet plugins and turning off event listeners

- package-lock.json
- package.json
- public/directives/savedSearches.html
- public/directives/wmsOverlays.html
- public/lib/leaflet.measurescale/L.Control.MeasureScale.js
- public/lib/leaflet.setview/L.Control.SetView.js
**WMS Ordering in action:**
**POI Ordering in action:**
> Dynamic Ordering of WMS and POI layers

- docs/siren_api/README.md
- gulpfile.js
- package-lock.json
- package.json
- public/siren_api.js
- public/vis.js
- public/visController.js
This PR adds the ability to send geoJSON collection from the script
> Scripting - registered the renderGeoJsonCollection

- public/visController.js
fix for -  https://github.com/sirensolutions/kibi-internal/issues/10948
> Moving popup field logic so that they work for scripting geoJsons

- public/POIs.js
- public/directives/savedSearch.html
- public/directives/savedSearch.js
- public/visController.js
- public/vislib/_map.js
This PR addresses (they were related so I closed the enhancement previously):
This enhancement - https://github.com/sirensolutions/kibi-internal/issues/10285
This bug - https://github.com/sirensolutions/kibi-internal/issues/10781
Tested on - page load, apply changes, on dashboard and edit mode.
> Custom name improvement + search name as default

- public/vis.js
- public/visController.js
part of close https://github.com/sirensolutions/kibi-internal/issues/10995
> register actions for version 1

- public/POIs.js
- public/directives/savedSearch.html
- public/vector.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
Fix for: https://github.com/sirensolutions/kibi-internal/issues/10777
Tested with Aggregations, and points and polygons fro POI and Vector sources:
> Disabling popups when in draw mode

- public/POIs.js
- public/callbacks.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
> [Backport to 10.3.x] POI popup flicker

- public/POIs.js
- public/callbacks.js
- public/directives/savedSearch.html
- public/directives/savedSearch.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
Backport of: https://github.com/sirensolutions/kibi-internal/issues/10781
> [Backport to 10.3.x] Custom name and search name as default for POI layers

- public/POIs.js
- public/directives/savedSearch.html
- public/directives/savedSearch.js
- public/vis.less
- public/visController.js
- public/vislib/_map.js
- public/vislib/searchIcon.js
https://github.com/sirensolutions/kibi-internal/issues/10778
> [Backport to 10.3.x] Icons instead of markers the data model for POI layers

- public/POIs.js
- public/directives/savedSearch.html
- public/vislib/_map.js
- public/vislib/geoFilter.js
- public/vislib/geoFilterHelper.js
- public/vislib/geoFilterModal/geoFilterModal.js
- public/vislib/marker_types/base_marker.js
https://github.com/sirensolutions/kibi-internal/issues/10777
> [Backport to 10.3.x] Disabling popups when in draw mode and adding React GeoFilter modal (to fix meta errors)

- public/vislib/geoFilter.js
- public/vislib/geoFilterHelper.js
issue: https://github.com/sirensolutions/kibi-internal/issues/11134
> Tidying up of geofilter.js and helper file

- gulpfile.js
- package-lock.json
- package.json
https://github.com/sirensolutions/kibi-internal/issues/10819
Bumped gulp version from 13.9.1 to 14.0.2
> Bumped gulp version from 13.9.1 to 14.0.2

- public/POIs.js
- public/backwardsCompatible.js
- public/lib/leaflet.groupedlayercontrol/groupedlayerscontrol.js
- public/vis.html
- public/vis.js
- public/vis.less
- public/visController.js
- public/vislib/_map.js
- public/vislib/geoFilter.js
- public/vislib/modals/genericModal.js
- public/vislib/searchIcon.js
New feature for drag and drop of POI layers  
**This needs to be merged with https://github.com/sirensolutions/kibi-internal/pull/11064** - already approved. 
The following issues can be closed as a result of this:
https://github.com/sirensolutions/kibi-internal/issues/11028
https://github.com/sirensolutions/kibi-internal/issues/11146
> Drag and Drop for POI layers

- public/vector.js
Fix for - https://github.com/sirensolutions/kibi-internal/issues/11190
Problem solved.
> Popups not closing on mouseout

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Also, bump gradle to 2.14.1
For https://github.com/sirensolutions/kibi-distribution/issues/1610
> Use gradle artifactory cache

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Also bump gradle to 2.14.1
For https://github.com/sirensolutions/kibi-distribution/issues/1610
> [port][10.3.x] Use gradle artifactory cache

- public/callbacks.js
- public/visController.js
close https://github.com/sirensolutions/kibi-internal/issues/11419
> Query now fired each time map is zoomed or dragged if no docs present

- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
fix for - https://github.com/sirensolutions/kibi-internal/issues/11415
Tested by checking/unchecking and saving the dashboard of the following layer types:
WMS, 
POI,
Aggregations, 
WFS, 
Applied Filters
Fix for  https://github.com/sirensolutions/kibi-internal/issues/11416 change is also in here:
https://files.slack.com/files-pri/T0ST06F7X-FQS4Y3UU9/image.png
> :Saving visibility state of all layer types

- public/callbacks.js
- public/utils.js
- public/visController.js
- public/vislib/DataBoundsHelper.js
- public/vislib/_map.js
Fix for: https://github.com/sirensolutions/kibi-internal/issues/11484
Tested:
On dashboard (including join filter)
On vis edit mode
> [WIP] - Fit data to bounds now includes data from outside of current map canvas

- .eslintrc
- .eslintrc.yml
- gulpfile.js
- package-lock.json
- package.json
- public/__tests__/resp_processor.js
- public/directives/tooltipFormatter.js
- public/lib/angular-bootstrap/js/accordion-tpls.js
- public/lib/jquery.minicolors/jquery.minicolors.js
- public/lib/jquery.minicolors/minicolors.js
- public/lib/leaflet.groupedlayercontrol/groupedlayerscontrol.js
- public/lib/leaflet.measurescale/L.Control.MeasureScale.js
- public/lib/leaflet.setview/L.Control.SetView.js
- public/lib/leaflet.sync/L.Map.Sync.js
- public/resp_processor.js
- public/tooltip/popupVisualize.js
- public/vislib/LDrawToolbench.js
- public/vislib/__tests__/callbacks.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
- public/vislib/marker_types/geohash_grid.js
- public/vislib/marker_types/heatmap.js
- public/vislib/marker_types/scaled_circles.js
- public/vislib/marker_types/shaded_circles.js
- public/vislib/modals/genericModal.js
https://github.com/sirensolutions/kibi-internal/issues/11412
> updated with coding standard depending on eslint

- public/callbacks.js
- public/options.html
- public/vis.js
- public/visController.js
- public/vislib/DataBoundsHelper.js
- public/vislib/_map.js
To be merged with - https://github.com/sirensolutions/kibi-internal/pull/11590
Fix for: 
https://github.com/sirensolutions/kibi-internal/issues/11574
https://github.com/sirensolutions/kibi-internal/issues/11595 - desaturate WMS fix
Also courier.fetch replaced wit searchSource.fetch on mapzoom and mapmoveend so that less information is transferred
**Testing**
I've tested, changing time and querybar filters in dashboard and edit mode and auto fit does apply
The auto fit does not apply when user zooms and pans the map.
> Auto fitting data to bounds

- .eslintrc.yml
- public/POIs.js
- public/backwardsCompatible.js
- public/directives/savedSearch.js
- public/directives/wfsOverlay.js
- public/directives/wmsOverlay.js
- public/vector.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
Fix for - https://sirensolutions.atlassian.net/browse/INVE-285
> [INVE-285] Using uuid as layer keys

- package.json
By habit, I forgot to commit package.json file.
> Adding linter to package.json

- public/vis.less
- public/vislib/_map.js
This PR adds checkboxes on the layer control groups:
> Adding grouped layer control check boxes

- public/POIs.js
- public/tooltip/visTooltip.js
- public/utils.js
- public/vector.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
Fix for - https://sirensolutions.atlassian.net/browse/INVE-227
To Be Merged With - https://github.com/sirensolutions/kibi-internal/pull/11776
Tested drag and drop and vis param poi source types
Also includes fix where poi layer draws if it has just been created
> POI layers now working with DB 360

- public/POIs.js
- public/utils.js
Popup stays open when tooltip is hovered onto
> Popup stays open when tooltip is hovered onto

- package-lock.json
- package.json
Added versioning to the scripting interface
> Scripting Interface added version v1.0.0

- public/POIs.js
- public/tooltip/popupVisualize.js
- Minor changes: new hit count format
> [ES7 Compatibility]

- package-lock.json
- package.json
Based on sirensolutions/scripting-interfaces#12
> Updated scripting interface

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/vis.less
Fixes [INVE-996] minimizing and animation issue. 
[INVE-996]: https://sirensolutions.atlassian.net/browse/INVE-996
> Fix minimizing issue

- package-lock.json
- package.json
Jira issue: https://sirensolutions.atlassian.net/browse/INVE-705
> [INVE-705] Updated scripting interfaces dependency.

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/euiTreeViewCheckbox.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
- public/vislib/vector_layer_types/POIs.js
> Checkboxes and counts working

- public/lib/dragAndDroplayercontrol/euiTreeViewCheckbox.js
> Expand tree view by default

- public/lib/dragAndDroplayercontrol/layerContolTree.js
Fixes [INVE-1032]. Removes "All Layer" (Eg: AllCounties, AllCountries) when count is 0.
[INVE-1032]: https://sirensolutions.atlassian.net/browse/INVE-1032
> Remove All Layer counts

- public/lib/dragAndDroplayercontrol/layerContolTree.js
- public/vis.less
> Searchbar functionality

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/euiTreeViewCheckbox.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
- public/lib/dragAndDroplayercontrol/uiLayerControlDnd.js
- public/utils.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/vector_layer_types/EsLayer.js
- public/vislib/vector_layer_types/POIs.js
I set the limit to be very low for testing purposes, the limit is set to 1000 points in the PR
> Warning Icons appears on stored layers for when there are unreturned documents

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/vis.less
Fixes: [INVE-991]
[INVE-991]: https://sirensolutions.atlassian.net/browse/INVE-991
> Scrollable layers fix

- public/vislib/vector_layer_types/POIs.js
fix for - https://sirensolutions.atlassian.net/browse/INVE-977
> Map extent filter applied to POI layers

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/visController.js
- public/vislib/marker_types/base_marker.js
- public/vislib/vector_layer_types/EsLayer.js
- public/vislib/vector_layer_types/POIs.js
- public/vislib/vector_layer_types/vector.js
> Memory leak fix part 1, and bug fixes

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/vis.less
- public/vislib/vector_layer_types/POIs.js
Centering the Add Layers button and making it fit more with the layer control
> Style add layers button

- package-lock.json
- package.json
We do NOT need it as kibi-internal now has 22.1.0
> Drop custom EUI dependency 

- package-lock.json
- package.json
@corrigancd was there any particular reason we used the version higher than that one used in kibi-internal?
> drop react-dom as we ship one in kibi-internal

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/vis.less
> made the layers window smaller

- public/vislib/_map.js
The issue with the export of enhanced tilemap visualization.
[INVE-11081]
[INVE-11081]: https://sirensolutions.atlassian.net/browse/INVE-11081
> Fix for issue in exporting enhanced tilemap

- public/lib/dragAndDroplayercontrol/layerContolTree.js
fix for - https://sirensolutions.atlassian.net/browse/INVE-11209
> Layer control tree checkboxes unchecked by default

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/__tests__/DndLayerControl.js
> Some unit tests for DndLayerControl.js

- .eslintrc.yml
- public/callbacks.js
- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/__tests__/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/__tests__/layerControlTree.js
- public/lib/dragAndDroplayercontrol/__tests__/uiLayerControlDnd.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
- public/vislib/vector_layer_types/EsLayer.js
- public/vislib/vector_layer_types/vector.js
Reduced redraws of map layers while
- Panning or zooming on map
- Adding layers from layer control tree
- Enabling/Reordering layers on map 
[Map Layer Control.drawio.zip](https://github.com/sirensolutions/enhanced_tilemap/files/4540988/Map.Layer.Control.drawio.zip)
> Map optimizations

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/euiTreeViewCheckbox.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
fix for - https://sirensolutions.atlassian.net/browse/INVE-11268
> Graying out items on modal if they are already on map

- package-lock.json
- package.json
- public/lib/dragAndDroplayercontrol/uiLayerControlDnd.js
- public/vis.less
The brief is that we need a way to identify that layers are a Stored Layer type, how about this: 
Option 1:
> Indicating that a layer is a stored layer type

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/uiLayerControlDnd.js
- public/visController.js
Wrapped private variables and methods in a function.
Fix for [INVE-11315]
[INVE-11315]: https://sirensolutions.atlassian.net/browse/INVE-11315
> Fix multiple maps on same dashboard

- public/backwardsCompatible.js
addressing - https://sirensolutions.atlassian.net/browse/INVE-11335
> Persisting storeLayersConfig array variable to vis state if one does not already exist

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/__tests__/layerControlTree.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
- public/vislib/vector_layer_types/EsLayer.js
Min and max zoom working from default configuration:
> Cascading Configurations for Stored layer types

- public/vislib/vector_layer_types/EsLayer.js
- public/vislib/vector_layer_types/vector.js
fix for - https://sirensolutions.atlassian.net/browse/INVE-11356
> Using same popup logic for polyons that is used for points

- public/vis.less
- public/vislib/vector_layer_types/POIs.js
Drag and drop poi layers working now:
> Drag and drop poi layer fix

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/__tests__/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/__tests__/uiLayerControlDnd.js
- public/visController.js
- public/vislib/vector_layer_types/EsLayer.js
- public/vislib/vector_layer_types/POIs.js
Current progress, I think it's done, need more testing and tidying up
> Specifying field to use in config for layer types

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/__tests__/layerControlTree.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
- public/visController.js
- public/vislib/_map.js
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11429
Tested in vis edit mode, dashboard and dashboard full screen mode. Deleting layers by clicking the bins also works: 
@szydan, I'm storing a string in the uiState rather than boolean. We need to know both if a layer is present, and also if it should be enabled on the map.
> Storing stored layer visibility in vis uiState

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/visController.js
> UiState registered for stored layers added to map but not enabled

- public/vis.html
- public/vis.less
Fix for issue raised here [INVE-11132] - we will review and merge when main UX branch in kibi-internal is merged
[INVE-11132]: https://sirensolutions.atlassian.net/browse/INVE-11132
> INVE-11132 - Negative margin to remove padding introduced in viz container

- public/tooltip/visTooltip.js
@johnnylopes , @poojah1 fix for - https://sirensolutions.atlassian.net/browse/INVE-11452
> Fix for screen crash with geohash

- public/vis.less
> Icon alignment

- public/lib/dragAndDroplayercontrol/uiLayerControlDnd.js
- public/vis.less
- public/vislib/vector_layer_types/EsLayer.js
Update default color of drag icons (=) so that they are visible (not sure if they are white by design. Ignore this PR if so.)
> Update drag icon color

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/vislib/vector_layer_types/EsLayer.js
[INVE-11474](https://sirensolutions.atlassian.net/browse/INVE-11474)
> Map layers popup - allow strings

- public/vislib/icons/markerClusteringIcon.js
- public/vislib/icons/searchIcon.js
> Adding ids for integration tests

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/visController.js
Jira issue: https://sirensolutions.atlassian.net/browse/INVE-597
Related PRs:
- https://github.com/sirensolutions/kibi-internal/pull/12197
These changes prevent the overlay from remaining stuck on the map when releasing a dashboard quickly after starting dragging it (which only occurred when the dashboard being dragged didn't have a geo field). This PR also fixes a couple console errors and a typo.
> [INVE-597] Fixed dashboard dragging overlay and some console errors.

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/vislib/vector_layer_types/EsLayer.js
> [INVE-11557] ETM Polyline support

- docs/modules/siren-investigate/pages/enhanced_tilemap.adoc
[INVE-11560](https://sirensolutions.atlassian.net/browse/INVE-11560)
To be merged together with #263
> Map layers polyline ingestion  -  docs update

- docs/modules/siren-investigate/pages/enhanced_tilemap.adoc
This is a PR for updating polyline map rendering docs.
> [INVE-11559] Polyline rendering - docs update

- public/tooltip/visTooltip.js
- public/visController.js
Should be merged after/together with https://github.com/sirensolutions/kibi-internal/pull/12366
> Filter visualization tooltip now applies to other visualization the dashboard

- docs/antora.yml
This updates the docs version to major.minor
> [INVE-12038][10.5.x] Update docs reference

- docs/antora.yml
This updates the docs version to major.minor
> [INVE-12038] Update docs reference
