sirensolutions/enhanced_tilemap

- public/vis.js
Will be used in Investigate to show this plugin is in BETA stage once https://github.com/sirensolutions/kibi-internal/pull/6847 is merged.
(See the start of the gif)
> Add isBeta flag and remove [BETA] prefix from description

- build.gradle
For use during the build process where a custom version can be specified when a package with experimental changes needs to be built.
> Adding support for customVersion and customInvestigateVersion parameters

- public/tooltip/popupVisualize.js
- public/tooltip/visTooltip.js
- public/vis.less
- public/visController.js
Backport of sirensolutions/kibi-internal/issues/9357 for https://github.com/sirensolutions/kibi-internal/issues/9656
Cherry picked from 2 commits. Verified that it fixes the issue manually, i.e. the record table visualization tool-tip now appears (with working query filters) with this PR for 10.2.x branch (image below).
> Backport of 9347 to 10.2.x branch

- public/POIs.js
This change fixed both POI issues below: 
https://github.com/sirensolutions/kibi-internal/issues/9800
https://github.com/sirensolutions/kibi-internal/issues/9803
> Replacing rather than appending map extent bounds when "Apply Filters" is ticked

- public/options.html
@colmose asked you for review as you raised a very similar issue to point 1 - https://github.com/sirensolutions/kibi-internal/issues/6826
This PR addresses 2 issues that are related to the same tool tip:
1. https://github.com/sirensolutions/kibi-internal/issues/9263 - The issue is that the tooltip is hidden as the default tooltip placement is "top". I changed it to "right" and the entire tooltip is visible as below: 
2. https://github.com/sirensolutions/kibi-internal/issues/9245 - I think this tooltip is mixed up and I investigated (below is the original tooltip text, and top orienatation): 
"A value too small could result in excessive fetches" - To me if the map collar scale is set to small number there will be less fetches
"A value too large could result in trimmed results and slow …
> Altering map collarscale tooltip (placement and text)

- public/lib/leaflet.groupedlayercontrol/groupedlayerscontrol.js
- public/vis.less
- public/vislib/_map.js
**Addressing:** 
https://github.com/sirensolutions/kibi-internal/issues/9802
How it looks when there are POI and WMS layers present: 
How it looks when one of the groups is removed (heading is also removed): 
See comment at the top of added file for justification of adding it
> Layer control groups for different overlay categories

- public/directives/wmsOverlay.js
The change removes this error appearing in the console:
> More stringent check which removes a console error

- public/callbacks.js
- public/visController.js
- public/vislib/_map.js
https://github.com/sirensolutions/kibi-internal/issues/6833
WIP because the WMS layer control group appears at the top of the POI layers on page refresh. Then when it is re-rendered, it changes to below the POI layers. 
Had to remove the checkbox option for groups for now also
> Fix for WMS layer not appearing

- public/visController.js
- public/vislib/_map.js
https://github.com/sirensolutions/kibi-internal/issues/10263
I investigated this in the Enhanced TileMap plugin (there is naming confustion, it is the same vis. as enhanced coordinate map). I found two issues and this PR fixes both: 
1. Base layer (either default OSM or the one specified in vis params) only rendered on page load. 
2. Map did not desaturate/saturate based on saved vis.params on page load.
I've tested manually with the following combinations and all works as expected: 
(Page load / Vis params changes applied) **with** (deSaturated ticked / deSaturated unticked) **AND** (WMS compliant map server:  ticked / unticked)
> Fixing WMS compliant map server and saturation on page load

- public/vislib/_map.js
Checked the export from dashboard with this PR and it was successful
To be merged with: 
https://github.com/sirensolutions/kibi-integration/pull/925
https://github.com/sirensolutions/kibi-internal/pull/10338
> Issue 10336 - removal of mixed-content errors so that exporting of ETM vis will work on dashboard

- public/utils.js
- public/vis.less
- public/vislib/marker_types/base_marker.js
Currently the popup remains open from marker mouseoff to popup mouseon: 
The next step is making the visualization interactive, i.e. so the scroll bar will work.
The barrier is that the CSS currently finds "leaflet-popup" pointer-event when the popup is hovered on. This means that the event is finding the leaflet-popup div as below, i.e. ... without the interactive-popup class: 
```<div class="leaflet-popup leaflet-zoom-animated" style="transform: translate3d(-28px, -191px, 0px); bottom: -16px; left: -167px;"><a class="leaflet-popup-close-button" href="#close">×</a>```
If you untick "close tooltip on mouseout", then the popup is interactive, the only difference seems to be that 'interactive-popup' is included in the class name: 
```<div class="leaflet-popup interactive-popup …
```
> [WIP] - Mouse on to popup visualization and interactivity with visualization

- public/callbacks.js
I missed a scenario when adding meta for dashboard 360 compatibility. If a user adds a geo filter in edit mode, there is a crash. 
Tested this commit in edit mode with polygon, rectangle and circle.
> Handling case when no meta present in vis edit mode

- public/callbacks.js
- public/vislib/__tests__/callbacks.js
- public/vislib/__tests__/fakePolygonObjects.js
Fix for: https://github.com/sirensolutions/kibi-internal/issues/10415
Previously, clicking on the green square resulted in a malformed polygon error. Now there is no error. 
I've also tested the original use case where it was necessary to add the initial vertex to the end of the array:
> Making sure the first polygon vertex is the same as the last

- public/directives/savedSearch.html
- public/directives/savedSearch.js
- public/vislib/marker_types/base_marker.js
How it looks now in GIF below. There was also an issue where the list repopulated when the page was refreshed, meaning that it was possible to add the same field twice (or more times if you refresh again), this has also been addressed.
> Tidying up UI and fixing selection pool list on page refresh

- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/heatmap.js
Fix for: https://github.com/sirensolutions/kibi-internal/issues/10395
I've tried many combinations of page refresh, changing marker type, toggling show tooltip on/off etc. Looks good:
> Removal of event listeners when heatmap show tooltip is false

- public/vislib/geoFilter.js
- public/vislib/geoFilterModal/geoFilterModal.js
I've tested with: 
- filters created from WFS geoJsons 
- on no linked search dashboard
- on single search dashboard
- on Dashboard360
- in vis edit mode 
**Dashboard 360 - note that the geofilters of each search are treated independently:** 
**Dashboard with no linked search - not that the filters applied of one search are applied to all:**
> Create filters option on modal

- public/directives/wmsOverlay.html
- public/visController.js
Fix for - https://github.com/sirensolutions/kibi-internal/issues/10951
All seems to be working:
Also tried ticking and unticking checkboxes in layer control
> Option whether a WMS layer is drawn on visualization load

- public/POIs.js
- public/directives/savedSearch.html
- public/directives/savedSearch.js
- public/vis.less
- public/visController.js
- public/vislib/_map.js
- public/vislib/searchIcon.js
Note - this may need to be rebased with master when the rest of the ETM PRs are merged
Works for all use cases I've tried. The UI change is whether a geo_point or geo_shape field is selected. 
If a geo_point field is selected, then the user sees an option to select an icon size. 
If a geo_shape field is selected, then the user sees an option to select the color for the polygon.  
The feature can be seen in the gif below (icon also appears in the layer control, not shown in GIF):
> Icons working with appropriate UI changes

- gulpfile.js
- package-lock.json
- package.json
Reverts sirensolutions/enhanced_tilemap#104
reverting as I hit 
```
szydan at hall in ~/home/workspace-scripting/enhanced_tilemap on master
$ gulp sync 
[17:28:10] Using gulpfile ~/home/workspace-scripting/enhanced_tilemap/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
gulpInst.start.apply(gulpInst, toRun);
^
TypeError: Cannot read property 'apply' of undefined
at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
at process._tickCallback (internal/process/next_tick.js:61:11)
at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
at startup (internal/bootstrap/node.js:282:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
> Revert "Bumped gulp version from 13.9.1 to 14.0.2"

- public/vis.html
- public/visController.js
Has to be merged after a sister PR in kibi-internal https://github.com/sirensolutions/kibi-internal/pull/11207
Now POI overlays only render on the layer they are dragged to. 
Working:
> Drag and drop - Handling case of more than one ETM on a dashboard

- build.gradle
Based on [this answer](https://github.com/srs/gradle-node-plugin/issues/190#issuecomment-285526889), I think what is happening is that the `.gradle` folder in the downloaded and extracted investigate-core is clashing with the `.gradle` inside enhanced-tilemap. 
So the change is to exclude the `.gradle` folder from investigate-core when extracting it. 
I'm thinking we don't need the gradle setup inside investigate-core at all and should remove the whole thing but that would need some more testing.
Tested and working in https://build6.siren.io/job/snapshot/job/full-build/2752/console
> Exclude the .gradle folder when extracting investigatecore

- public/visController.js
- public/vislib/marker_types/base_marker.js
Fix for - https://github.com/sirensolutions/kibi-internal/issues/11430
I handled the case of no buckets by creating a blank leaflet geoJson object for such cases. Then if there are buckets, the normal behaviour is executed.
> Fixing layer control flickering when no aggregation layer present

- public/vislib/geoFilter.js
Fix for: https://github.com/sirensolutions/kibi-internal/issues/11447
The screen now does not explode and filters work as intended:
> Handling case for join filter meta in geofilter assembly

- public/visController.js
Fix for: https://github.com/sirensolutions/kibi-internal/issues/11414
To be merged with: https://github.com/sirensolutions/kibi-internal/pull/11462
Checked with join filter also.
> Map now appears even when there are no dashboards present

- public/callbacks.js
- public/vislib/geoFilter.js
Fix for - https://github.com/sirensolutions/kibi-internal/issues/10803
Partial fix for - https://github.com/sirensolutions/kibi-internal/issues/11463. The reason it's a partial fix is that there are likely to be many POIs and a pill for each of these still isn't acceptable. I would suggest merging this for now and adapting the issue to include the bigger case of adding bool should  filter:
> Circle filter types render on map. Partial fix for POI geo_distance filter

- public/lib/leaflet.setview/L.Control.SetView.js
Fix for  = https://github.com/sirensolutions/kibi-internal/issues/11499
I was being specific in terms of event listener cleanup. According to leaflet docs, the method of event listener removal that I have changed for this PR is sufficient to remove the listeners when the app is destroyed - https://leafletjs.com/reference-1.6.0.html#evented-off
Lat and Lon Set View tool working:
> Fixing SetView Tool

- public/callbacks.js
- public/visController.js
- public/vislib/__tests__/fakeCallbackObjects/fakePolygonObjects.js
- public/vislib/_map.js
fix for - https://github.com/sirensolutions/kibi-internal/issues/11535
There was a return function if aggregations were not present as part of the event. This return function has been removed on the draw polygon, circle, rectangle, etc, events. This is ok to do as for the most part the only thing that was being retrieved from the event aggs object was index pattern id which is now retrieved from the visController scope instead.
I've tested with geoserver geoJsons also:
> geoFilters now created when no data present on map

- public/options.html
- public/vis.js
- public/visController.js
- public/vislib/_map.js
Fix for: 
https://github.com/sirensolutions/kibi-internal/issues/11575
https://sirensolutions.atlassian.net/browse/INVE-101
The Default is for the sync maps checkbox NOT to be ticked: 
In the GIF below: 
Top left = companies search with sync turned ON
Top right  = companies search with sync turned OFF
Bottom left = polygontest2 search with sync turned ON
Bottom right = polygontest2 search with sync turned OFF
> Option to sync maps in vis edit mode

- public/vislib/geoFilter.js
Fix for: https://github.com/sirensolutions/kibi-internal/issues/11598
@dgilliga, this should fix that problem. It's a fix that was done for skyhook a few weeks ago.
> Fixing app crash when creating geoFilter and join filter present

- public/tooltip/visTooltip.js
- public/visController.js
- public/vislib/marker_types/geohash_grid.js
- public/vislib/marker_types/shaded_circles.js
Fix for - https://github.com/sirensolutions/kibi-internal/issues/11536
To be merged with - https://github.com/sirensolutions/kibi-internal/pull/11629
Note that the records in the record table within the map correspond to the record table on the dashboard when a rectangular filter is created:
> Record table now appearing as tooltip popup when join filter is present on dashboard

- public/POIs.js
- public/tooltip/searchTooltip.js
- public/tooltip/visTooltip.js
- public/utils.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
- public/vislib/marker_types/geohash_grid.js
- public/vislib/marker_types/heatmap.js
- public/vislib/marker_types/scaled_circles.js
Addressing https://github.com/sirensolutions/kibi-internal/issues/11579. Needs to be rebased with master after #145 is merged.
I went through the entire repo, taking notes on what features would be affected by this change. The below have been manually tested:
- Aggregation legend and slider
- Aggregation tooltips (both on mouseover and mouseout)
- All events with and without data present on map i.e. set view, fitdata, autofitdata, filter creation
- Applied filters draw and can be toggled on layer control
- WMS and WFS work
- Destroy method don't produce console errors
- Map move end and map zoom end events
Also included in this fix are small cases where there were console errors relating to some recent features.
> Changing reference to leaflet map object from map to leafletMap

- public/directives/wfsOverlay.html
- public/directives/wfsOverlay.js
- public/directives/wmsOverlay.html
- public/visController.js
A UI change to allow any outputFormat type to be specified. The WFS feature currently supports json or geojson types however and warning messages will be generated if 
- another format is specified
- the server doesn't provide a valid response
> Adding geojson support for wfs requests

- public/directives/wfsOverlay.html
- public/directives/wfsOverlay.js
- public/directives/wmsOverlay.js
- public/vector.js
- public/vis.less
- public/visController.js
- public/vislib/_map.js
Layer labelling should be fixed. Pay attention to Texas and observe that the state name is repeated multiple times. When I select non-tiled layer, observe that the label is specified just once: 
I also adjusted the requests to WMS and WFS. Although they worked for GeoServer previously, they should be robust enough to work for any type of WMS/WFS server now. I've asked Tom in PAX to verify two links that I've tailored for their system, if all well, happy to merge this.
> [WIP] - Desaturating non-tiled WMS layers

- public/vislib/marker_types/heatmap.js
https://sirensolutions.atlassian.net/browse/INVE-738 - This is the only aggregation type that hasn't been configured to work with not data present on map canvas
> Heatmap works with no data present on map

- build.gradle
…ndencies
semantic-release has npm as a dependency, so after running gulpTest `node_modules` contains npm.
When running `gulpPackage`, node will use the `npm` installed in `node_modules`, which will destroy itself when removing `node_modules` and complain about the missing modules that it just destroyed.
To work around this autophagy mechanism try to remove npm from node_modules after installing dependencies.
> Remove npm from node_modules after installing dependencies

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/visController.js
This avoids an error in console when the map is not fully configured in Visualize (i.e. the geohash field has not been specified)
> Pass null mainSearchDetails while a map is being configured

- package-lock.json
- public/callbacks.js
- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
- public/visController.js
- public/vislib/vector_layer_types/EsLayer.js
- public/vislib/vector_layer_types/POIs.js
- public/vislib/vector_layer_types/vector.js
Three items addressed: 
1. Removal of for loop break in layer control tree _getItems() - The problem was that subsequent items in the array can have the required item, so the break needed to be removed
2. Multipolygon filters now working for ES layer sources - uses the same logic for filter creation as WFS geoJSONs do
3. POI filter logic changed (again) - so the previous fix meant that filters applied to POIs do not work when in edit mode. So this time, the searchsource.filters are used when on dashboard, and the queryFilter.getFilters() filters are used when in edit mode. Note - this will require a backport (again)
> Fixing case wher multipolygon type filters didn't work and small fix in getItems layer tree function

- build.gradle
Enhanced tilemap builds are [failing](https://build.siren.io/view/Snapshots/job/snapshot/job/plugins/job/enhanced-tilemap/2094/console) - this might not fix it but worth adding in any case. 
This uses the node version installed into the jenkins slave rather than pulling a new node instance each time. Have seen similar issues previously which were stabilised by this. 
https://build.siren.io/view/Snapshots/job/snapshot/job/plugins/job/enhanced-tilemap/2094/console
> Stop downloading node

- public/lib/dragAndDroplayercontrol/euiTreeViewCheckbox.js
Added wrapper div with `.euiTreeView__nodeInner`
> Fix treeview css issue

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
Single debounce handler for `zoom-end` and `move-end` events. 
_Color change shows re-render (Not checked in)_
> Draw all layers once on move-end or zoom-end

- public/lib/dragAndDroplayercontrol/layerContolTree.js
> Specifying larger bucket size for tree aggs query

- public/lib/dragAndDroplayercontrol/uiLayerControlDnd.js
- public/vis.less
> Tooltip now appearing if there is an ellipsis for long layer names

- public/lib/dragAndDroplayercontrol/layerContolTree.js
So the changes are:
- The add layers button is now filled while the add and enable button is empty (it used to be the other way around)
- If there are more than 35 layer checkboxes ticked (i.e. the performance threshold and to avoid browser crash), the Add and Enable button will be greyed out. I have tested this with a threshold of 4 as per GIF
> Adding threshold to Add And Enable button

- public/lib/dragAndDroplayercontrol/euiTreeViewCheckbox.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
I turned off the expand by default option the first time a group is whatever the opposite of expanded is
To be merged after - https://github.com/sirensolutions/enhanced_tilemap/pull/210
> Expand by default causing ui tree to be continuously open

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
@niknbr, heatmap is another case where zIndex is hard to set. This PR will mean that the heatmap layer will be drawn behind polygon layer types, but in front of tile layer types. Also tested with WMS layer.
> heatmap layer types sit on top of tile layers, but behind polygon layer types

- public/visController.js
- public/vislib/vector_layer_types/EsLayer.js
If stored layers is empty AND you add a stored layer: 
If there is a syntax error in stored layers, a toast will be displayed containing the console message, e.g.
> Better Error handling for stored layers config

- public/config/config.js
- public/directives/storedLayerConfig.js
fix for - https://sirensolutions.atlassian.net/browse/INVE-11395
When visualization loads (new, previous version or previous vis on current version) and the config field is empty string, the default will be added to the text area as below. If there is already one present, it will not update:
> use a default Stored Layer config if there is none defined

- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/heatmap.js
fix for - https://sirensolutions.atlassian.net/browse/INVE-11319
Heatmap popups work when changing vis params, panning and zooming the maps AND when toggling visibility on and off
> Heatmap popups now disappearing when disabling layer

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/euiTreeViewCheckbox.js
- public/lib/jquery.minicolors/jquery.minicolors.js
- public/visController.js
- public/vislib/_map.js
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11313
Some Notes -
* Events created in vis controller and dndlayercotrol.js are turned off in _map.js
* According to https://stackoverflow.com/questions/7549188/are-event-listeners-in-jquery-removed-automatically-when-you-remove-the-element, jquery events are removed automatically, so removed warnings from the jquery.minicolors.js file
* Added remove lint warning lines to euiTreeView.js warnings. The variables are actually/may acutally be used
> Removal of linting errors and warnings

- public/vislib/_map.js
Fix for second issue in - https://sirensolutions.atlassian.net/browse/INVE-11323
**Before this PR (when in edit mode):**
**With this PR:**
Option to add markers does not appear in edit mode
Nor does the Marker layer appear in edit or dashboard mode (screenshot captured in edit mode)
> Removal of markers from dashboard and edit mode

- public/vis.less
[INVE-11461] Fixes width issue in Firefox (fit width not supported, also a fixed width is generally better) and removed height from button (it changes standard EUI styles and is inconsistent)
[INVE-11461]: https://sirensolutions.atlassian.net/browse/INVE-11461
> Set width instead of fit-content and removed height on button

- public/lib/dragAndDroplayercontrol/uiLayerControlDnd.js
- public/vis.less
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11518
@jccq requested change from vertical to horizontal grip handle similar to cards on gb: 
was: 
now:
> Drag handles changed from vertical to horizontal

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/uiLayerControlDnd.js
Fire leaflet `showLayer` event only when adding (with enabled) layers from layer control tree or toggling layers on the drag-and-drop layer control.
Fixes[INVE-11485]
[INVE-11485]: https://sirensolutions.atlassian.net/browse/INVE-11485
> Fire showLayer only when adding layer or toggling layers

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/lib/dragAndDroplayercontrol/layerContolTree.js
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11544
I've tested on an instance where there are stored layers present (normal kibi-distribution)and on an instance where there are no stored layers present (ssh to contact.demo.siren.io). There were no errors in logs on visualization load or when the add layers button is clicked. Both of those cases are where the error logs were happening. 
The fix was to return from get paths only if there is a valid response. Then populating the layer tree modal or loading stored layers on visualization processes are skipped if the response is undefined. 
Example of response where there are stored layers (there is an aggregations object in response):
Example of response where there are NOT stored layers (there is not an aggregations object in …
> Handling case where there are no stored layers present in ES

- public/callbacks.js
- public/visController.js
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11564
Previously, each time the map was zoomed or panned, auto precision being true meant that the fetch was executed. I've now created an if/else to handle cases with auto precision on and off. 
When panning: We need to fetch new data only if the new map canvas extent happens to be outside of the collar. If the new map canvas extent is within the collar scale bounds, the data from the previously executed fetch is sufficient. GIF below shows fetch only being executed when outside of the 1.5 collar scale (i.e. from USA to Europe): 
When changing zoom: If there is a change in zoom, we need to execute fetch as the current data may need to be updated to reflect the change in (zoom level based) precision.
> Fix for collar scale being ignored

- public/vislib/DataBoundsHelper.js
- public/vislib/__tests__/DataBoundsHelper.js
Previously, we zoomed to the graviatational centroid of the geohash. This was good for centering the data on the map, but it meant that latitude and longitude were the same for responses containing just 1 document. This change means that the bounds of the geohash(s) are fitted. So if there is 1, the containing geohash will be zoomed to. Then an ES query will be fired to show the aggregation on the map to the precision corresponding to that zoom level:
> Fitting bounds to geohashes containing data rather than centroid

- public/vislib/icons/markerClusteringIcon.js
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11640
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11646
To be merged after - https://github.com/sirensolutions/enhanced_tilemap/pull/256
Halo removed and colour ramp added as described in - https://sirensolutions.atlassian.net/browse/INVE-11640
There are clustering layers present on the map. Note that the 268 is dark as it has the highest count for the companies poi layer. While the trees layer has lighter colors for higher numbers (because 700k is the highest number for this layer)
> Marker clustering styling (part 2)

- public/vislib/vector_layer_types/EsLayer.js
This is a fix for map layer icons. 
1. Forgot to delete a line.
2. Fixed `if` statements and made them use direct comparison `===` rather than `.include()` 
With data
Without data
> [INVE-11883] Map layers icon fix

- public/directives/wmsOverlay.html
- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/visController.js
- public/vislib/_map.js
@jefersonzanim, @manu4387 , you asked me about this one in the last couple of weeks. 
XYZ tile servers should now be working again. @jefersonzanim would like to confirm that if the WMS url contains `{x}` AND `{y}` AND `{z}`, the url can be considered an XYZ tile server? This seems to be the case for all XYZ available on - https://leaflet-extras.github.io/leaflet-providers/preview/
The logic to convert the url into a WMS request is then skipped (which is the fix). This is a regression, and happened when making the WMS requests compatible with ArcGIS server a few months ago.  
Example XYZ url: 
https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
> XYZ layers and desaturate working with new layer control

- public/directives/wmsOverlay.js
- public/utils.js
- public/visController.js
- public/vislib/_map.js
Tried xyz's from here - https://leaflet-extras.github.io/leaflet-providers/preview/
WMS requests from my own geoserver
mapbox xyz request - https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZW5nY29kYSIsImEiOiJjanVxcGEzemcyOTZ3M3pueDg5b3Vzc25hIn0.59azAbNI5tb-JWyLp5RgKw
GetCapabilities request NOT fired for XYZ layer types
Toast for when XYZ url is detected with non-tiled layer type
There are optimisations that could be done to reduce network requests
> Revisiting XYZ tile servers

- public/vislib/vector_layer_types/EsLayer.js
Also accommodated are lines. The border color of a polygon (now grey-ish) is the same as the color of the actual line (now the configured color). Ternary functions determine the geometry type. 
I chose the slim grey line for polygon borders because it's similar to the QGIS default and I've found it to be easy to work with in the past. 
Previously:
With this PR:
> Restyling polygon borders and fill type

- public/__tests__/utils.js
- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/utils.js
- public/visController.js
With this PR, if the previous zoom extent had too many documents to be drawn on the map, the layer will be re-rendered when zooming in.
This applies to polygon and line type layers. 
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11993
> Redraw layer if too many document drawing on previous extent

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/tooltip/visTooltip.js
- public/visController.js
Backporting filters working with SID from master to 10.5.x. Tested manually with same tests used on master, looks ok. 
To be merged with - https://github.com/sirensolutions/kibi-internal/pull/12376
> [Backport 10.5.x] - ETM changes for sid instead of visid and pandel index vis tooltip filters

- public/callbacks.js
- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/vector_layer_types/EsLayer.js
Icon to create point buffer filter now appears when: 
* There are less than 100 point documents (in total) on the map
* There are no clusters present on the map
Filters are only created for the points that are visible on the map. 
Jarek, for manual test, you can set the map collar to 1 to make things easier.
> POI buffer filters for points fixed post marker clustering

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/utils.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/marker_types/base_marker.js
- public/vislib/session_state.js
The idea is to swap out session storage when uiState is refactored. What happens in this PR :
- Loading vis the sirenSession object is checked for presence of uiState, this is used if it is present. The id for each vis is `rootId` + `visId`
- If vis not present in siren session, then the regular uiState is used, if there is no uiState, the default state is used
- The uiState functionality is maintained throughout the visualization, i.e. the uiState is updated alongside the sessionState
Manual Testing (carried out by me):
**Note - you clear session state by refreshing browser**
**State refers to the visibility of layers visible/not visible stored layers, enabled/not enabled all layers, map zoom and the centre point of the map**
> Map center and zoom level from sessionStorage if available

- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/visController.js
- public/vislib/vector_layer_types/EsLayer.js
Before the warning icon drew and was then removed if a subsequent layer was drawn. Now each time an overlay is added, there is warning check and the icons is added or removed if necessary:
> Fixing too many documents layer control warning icon

- public/visController.js
- public/vislib/_map.js
I copied one of these into investigate.yml, restarted investigate and loaded an enhanced coordinate map visualization with WMS server turned off in Map options in edit mode. Then repeated the process for the second one (Investigate crashes with a duplicated key error if two are added). Seems fine: 
Mapbox url:
```
tilemap:
url: "https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZW5nY29kYSIsImEiOiJjanVxcGEzemcyOTZ3M3pueDg5b3Vzc25hIn0.59azAbNI5tb-JWyLp5RgKw"
options:
attribution: '[© Mapbox](https://www.mapbox.com/about/maps/)[© OpenStreetMap](http://www.openstreetmap.org/about/)'
minZoom: 0
maxZoom: 19
``` 
XYZ tile server from https://leaflet-extras.github.io/leaflet-providers/preview/ :
```
tilemap:
url: …
```
> Using tilemap server configured in investigate.yml

- docs/modules/siren-investigate/pages/enhanced_tilemap.adoc
Fixed typos and a problem with the formatting of a bulleted list. Also replaced the term 'ticked/unticked' with 'checked/unchecked'.
Before:
After:
> INVE-12195 Fix typos in enhanced tilemap topic

- public/__tests__/utils.js
- public/lib/dragAndDroplayercontrol/DndLayerControl.js
- public/utils.js
- public/visController.js
- public/vislib/_map.js
- public/vislib/vector_layer_types/EsLayer.js
- public/vislib/vector_layer_types/POIs.js
- public/vislib/vector_layer_types/vector.js
Fix for - https://sirensolutions.atlassian.net/browse/INVE-11718
To be merged with - https://github.com/sirensolutions/kibi-internal/pull/12477
Main fix:
- When map is panned/zoomed, relative time filter dashboards do not update, they stay the same as other visualizations on the dashboard
- Auto refresh dashboard is now also updates map layers (not stored layers as it is not their intention for now, was just for queryfilter bar previously)
- Map layers will update when time filter is changed (was just for queryfilter bar previously)
- Aggregation layer renders just once when panning/zooming map. Previously it rendered from `esResponse` watcher as well as manually from the `drawAggregationLayer` function. Now, the fetch is called from funciton and all rendering is handled in `esResponse` …
> Retaining dashboard time while panning/zooming the map
